# Generated by Django 5.2.4 on 2025-07-14 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("moncash_order_id", models.CharField(blank=True, max_length=100)),
                ("payment_token", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(blank=True, default="HTG", max_length=3)),
                (
                    "status",
                    models.CharField(blank=True, default="pending", max_length=20),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="moncash", max_length=50),
                ),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("transaction_date", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("callback_url", models.CharField(blank=True, max_length=255)),
                ("return_url", models.CharField(blank=True, max_length=255)),
                ("webhook_received_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
