# nixpacks.toml - Configuration corrigée pour Railway
[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql_14", "redis", "gcc", "pkg-config"]
aptPkgs = ["build-essential", "libpq-dev", "libjpeg-dev", "libpng-dev", "libwebp-dev"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput --clear",
  "python manage.py migrate"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"