# Generated by Django 5.2.4 on 2025-07-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(blank=True, default="website", max_length=50),
                ),
            ],
            options={
                "db_table": "newsletter_subscribers",
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("setting_key", models.CharField(max_length=100, unique=True)),
                ("setting_value", models.TextField(blank=True, null=True)),
                (
                    "setting_type",
                    models.CharField(blank=True, default="text", max_length=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "group_name",
                    models.CharField(blank=True, default="general", max_length=50),
                ),
                (
                    "is_public",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "site_settings",
            },
        ),
    ]
