# Generated by Django 5.2.4 on 2025-07-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.CharField(max_length=255)),
                ("image_path", models.CharField(max_length=255)),
                ("mobile_image_url", models.CharField(blank=True, max_length=255)),
                ("link_url", models.CharField(blank=True, max_length=255)),
                (
                    "button_text",
                    models.CharField(blank=True, default="Découvrir", max_length=50),
                ),
                (
                    "button_color",
                    models.CharField(blank=True, default="#007bff", max_length=7),
                ),
                (
                    "text_color",
                    models.CharField(blank=True, default="#ffffff", max_length=7),
                ),
                (
                    "overlay_opacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.3,
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, default=0, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("click_count", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "banners",
            },
        ),
        migrations.CreateModel(
            name="MediaContentSection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField()),
                ("detailed_description", models.TextField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=255)),
                ("image_path", models.CharField(blank=True, max_length=255)),
                (
                    "button_text",
                    models.CharField(
                        blank=True, default="Voir les produits", max_length=50
                    ),
                ),
                ("button_link", models.CharField(blank=True, max_length=255)),
                ("category_tags", models.TextField(blank=True, null=True)),
                ("product_tags", models.TextField(blank=True, null=True)),
                ("background_color", models.CharField(blank=True, max_length=7)),
                ("text_color", models.CharField(blank=True, max_length=7)),
                (
                    "layout_type",
                    models.CharField(blank=True, default="left", max_length=10),
                ),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "media_content_sections",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("excerpt", models.TextField(blank=True, null=True)),
                ("featured_image", models.CharField(blank=True, max_length=255)),
                (
                    "template",
                    models.CharField(blank=True, default="default", max_length=50),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "is_featured",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("sort_order", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pages",
            },
        ),
    ]
