# Generated by Django 5.2.4 on 2025-07-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("options", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cart_items",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_number", models.CharField(max_length=50, unique=True)),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(max_length=20)),
                ("shipping_address", models.TextField()),
                (
                    "shipping_city",
                    models.CharField(
                        blank=True, default="Port-au-Prince", max_length=50
                    ),
                ),
                (
                    "shipping_country",
                    models.CharField(blank=True, default="Haïti", max_length=50),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                ("billing_city", models.CharField(blank=True, max_length=50)),
                (
                    "billing_country",
                    models.CharField(blank=True, default="Haïti", max_length=50),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(blank=True, default="HTG", max_length=3)),
                (
                    "status",
                    models.CharField(blank=True, default="pending", max_length=20),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, default="pending", max_length=20),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="moncash", max_length=50),
                ),
                (
                    "shipping_method",
                    models.CharField(blank=True, default="standard", max_length=50),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("coupon_code", models.CharField(blank=True, max_length=50)),
                ("source", models.CharField(blank=True, default="web", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_name", models.CharField(max_length=200)),
                ("product_sku", models.CharField(blank=True, max_length=50)),
                ("product_image", models.CharField(blank=True, max_length=255)),
                ("product_options", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("old_status", models.CharField(blank=True, max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "order_status_history",
            },
        ),
    ]
